# Generated by Django 4.0.4 on 2022-06-04 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='highlight',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
